apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-microservice
  template:
    metadata:
      labels:
        app: frontend-microservice
    spec:
      containers:
      - name: frontend-microservice
        image: registry.gitlab.com/s.marotta10/cloud-kubernetes/frontend-microservice:$CI_COMMIT_SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
