version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5001:5432'
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - 'db'
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  db: